---
- name: Delete a record from infoblox
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Ensure host record doesn't exist in infoblox
      connection: local
      infoblox.nios_modules.nios_host_record:
        name: "{{ my_hostname }}.kmhp.com"
        state: absent
        provider: {}
