---
- name: Test connection to Infoblox and get new ip address
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: look up network view objects
      ansible.builtin.set_fact:
        networkviews: "{{ lookup('infoblox.nios_modules.nios_lookup', 'networkview') }}"
    
    - name: Print networkviews object
      ansible.builtin.debug:
        var: networkviews
  
    - name: Get next IP
      ansible.builtin.set_fact:
        ipv4addr: "{{ lookup('infoblox.nios_modules.nios_next_ip', '10.148.80.0/22') }}"

    - name: Print ip address
      ansible.builtin.debug:
        var: ipv4addr
