---
- name: Test connection to Infoblox and get new ip address
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Get next IP
      ansible.builtin.set_fact:
        ipv4addr: "{{ lookup('infoblox.nios_modules.nios_next_ip', '10.148.83.0/25', nnetwork_view='vlan633') }}"

    - name: Print ip address
      ansible.builtin.debug:
        var: ipv4addr
