---
- name: VM post-provisioning handler
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Add new host to temporary group in in-memory inventory
      ansible.builtin.add_host:
        host: "{{ my_hostname }}"
        groups:
          - "Just_Created_{{ input_os.split(' ')|first }}"

- name: Start post-provisioning tasks for new Linux virtual machine
  hosts: "Just_Created_{{ input_os.split(' ')|first }}"
  become: true
  gather_facts: false

  vars:
    linux_device_map:
      1: b
      2: c
      3: d
      4: e
      5: f
      6: g
      7: h
      8: i
      9: j
      10: k
  vars_files:
    - centrify_secret.yml

  tasks:
    - name: Ensure host is reachable after provisioning
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        delay: 0
        sleep: 1
        timeout: 600

    - name: Gather facts for new host
      ansible.builtin.setup:

    - name: Ensure resolv.conf.standard is copied to resolv.conf.standard
      ansible.builtin.copy:
        remote_src: true
        src: /etc/resolv.conf.standard
        dest: /etc/resolv.conf

    - name: Ensure resolv.conf.standard is deleted
      ansible.builtin.file:
        path: /etc/resolv.conf.standard
        state: absent

    - name: Ensure NetworkManager service is restarted
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

    - name: Include tasks for Linux post-provisioning - configure volumes and file systems
      when: disks is defined
      loop: "{{ disks }}"
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_disks.yml

    - name: Include tasks for Linux post-provisioning - register to Satellite
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_satellite.yml

    - name: Include tasks for Linux post-provisioning - install a package
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_install_package.yml
    
    - name: Include tasks for Linux post-provisioning - add to domain
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_domain.yml