---
- name: VM post-provisioning handler
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Add new host to temporary group in in-memory inventory
      ansible.builtin.add_host:
        host: "{{ my_hostname }}"
        groups:
          - "Just_Created_{{ input_os.split(' ')|first }}"

- name: Start post-provisioning tasks for new Linux virtual machine
  hosts: "Just_Created_{{ input_os.split(' ')|first }}"
  become: true
  gather_facts: false

  vars:
    linux_device_map:
      1: b
      2: c
      3: d
      4: e
      5: f
      6: g
      7: h
      8: i
      9: j
      10: k
  vars_files:
    - centrify_secret.yml

  #vars:
  #  domain_user: "" #not in here so i don't accidentally push to git
  #  domain_password: "" #not in here so i don't accidentally push to git

  tasks:
    - name: Ensure host is reachable after provisioning
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        delay: 0
        sleep: 1
        timeout: 600

    - name: Gather facts for new host
      ansible.builtin.setup:

    - name: Include task for Linux post-provisioning - configure volumes and file systems
      when: disks is defined
      loop: "{{ disks }}"
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_disks.yml

    - name: Include task for Linux post-provisioning - register to Satellite
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_satellite.yml
    
    - name: Include tasks for Linux post-provisioning - add to domain
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_domain.yml


- name: Start post-provisioning tasks for new Windows virtual machine
  hosts: "Just_Created_{{ input_os.split(' ')|first }}"
  become: true
  gather_facts: false
  connection: winrm
  become_method: runas

  vars:
    ansible_winrm_server_cert_validate: ignore
    input_disk_nums:
      - 2
      - 3

  tasks:

    - name: Ensure host is reachable after provisioning
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        delay: 0
        sleep: 1
        timeout: 600

    - name: Gather facts for new host
      ansible.builtin.setup:
      
    - name: Include tasks for Windows post-provisioning - Disks
      when: disks is defined
      loop: "{{ disks }}"
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_windows_disks.yml

    - name: Include tasks for Windows post-provisioning - Disks
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_windows_disks_domain.yml