---
- name: VM post-provisioning handler
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Add new host to temporary group in in-memory inventory
      ansible.bultin.add_host:
        host: "{{ my_hostname }}"
        groups:
          - "Just_Created_{{ input_os }}"

- name: Start post-provisioning tasks for new Linux virtual machine
  hosts: "Just_Created_{{ input_os }}"
  become: true
  gather_facts: true

  vars:
    linux_device_map:
      1: b
      2: c
      3: d
      4: e
      5: f
      6: g
      7: h
      8: i
      9: j
      10: k
  vars_files:
    - centrify_secret.yml

  #vars:
  #  domain_user: "" #not in here so i don't accidentally push to git
  #  domain_password: "" #not in here so i don't accidentally push to git

  tasks:
    - name: Include tasks for Linux post-provisioning - add to domain
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_domain.yml

    - name: Include task for Linux post-provisioning - configure volumes and file systems
      when: disks is defined
      loop: "{{ disks }}"
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_linux_disks.yml

- name: Start post-provisioning tasks for new Linux virtual machine
  hosts: "Just_Created_{{ input_os }}"
  become: true
  gather_facts: true
  connection: winrm
  become_method: runas

  tasks:
    - name: Include tasks for Windows post-provisioning
      ansible.builtin.include_tasks:
        file: tasks/post_provisioning_windows.yml