---
- name: Power off and rename VM in VMWare
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    vmw_datacenter: "CGV_NP_GC"
    vmw_folder: "Template"

  tasks:
    - name: Get UUID of VM in VMWare
      register: vm_info
      community.vmware.vmware_guest_info:
        datacenter: "{{ vmw_datacenter }}"
        folder: "{{ vmw_folder }}"
        name: "{{ my_hostname }}"

    - name: Dump VM guest info
      ansible.builtin.debug:
        var: vm_info

