---
- name: provison linux vm
  hosts: localhost
  become: false
  gather_facts: false
  
  tasks:
    - name: create vm from template
      community.vmware.vmware_guest:
        datacenter: "{{ dc }}"
        name: "{{ vm_name }}"
        template: "{{ template }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ folder }}"
        state: "{{ vm_state }}"
        
        
        
        
        
 
