---
- name: provison linux vm
  hosts: localhost
  become: false
  gather_facts: false
  
  tasks:
    - name: create vm from template
      community.vmware.vmware_guest:
        datacenter: "{{ dc }}"
        name: "{{ vm_name }}"
        template: "{{ template }}"
        cluster: "{{ cluster_name }}"
        folder: "{{ folder }}"
        state: "{{ vm_state }}"
        networks: "{{ vm_networks }}"
        hardware: 
          memory_mb: 8192
          num_cpus: 1
          num_cpu_cores_per_socket: 4
        datastore: CGVPUR701A1-NP-NRPL-VVOLS
        disk:
        - size_gb: 10
          controller_type: 'paravirtual'
          controller_number: 1
          unit_number: 0
        
        
        
        
        
 
