---
- name: Add specified host to in-memory inventory
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Add new host to temporary group in in-memory inventory
      when: input_os.find('Windows') != -1
      ansible.builtin.add_host:
        #host: "{{ my_hostname }}.kmhp.com"
        host: cgvx1wuatwe103.kmhp.com
        groups:
          - "Just_Created_{{ input_os.split(' ')|first }}"
  
- name: Start post-provisioning tasks for new Windows virtual machine
  hosts: "Just_Created_{{ input_os.split(' ')|first }}"
  #become: true
  gather_facts: false
  connection: winrm
  #become_method: runas

  tasks:
  - name: Join Windows domain
    ansible.windows.win_domain_membership:
      dns_domain_name: "KMHP.COM"
      domain_admin_password: "{{ win_ad_admin_password }}"
      domain_admin_user: "{{ win_ad_admin_user }}"
      domain_ou_path: "{{ win_ad_ou_path }}"
      hostname: "{{ my_hostname }}"
      state: workgroup
